[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200  ; Sets the Serial Monitor speed automatically
lib_deps =              ; List your libraries here, one per line
    bblanchon/ArduinoJson @ ^7.0.0