[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

; Standard baud rate for ESP32 and your UART config
monitor_speed = 115200

; CRITICAL: Decodes the backtrace if your ISR or Queue crashes
monitor_filters = esp32_exception_decoder

; Increase the upload speed to save time during development
upload_speed = 921600

; If you use C++ features in your .c files or vice versa
build_flags = 
    -D CORE_DEBUG_LEVEL=3